version: '3.4'

services:
  #maildev:
  #  ports:
  #    - "5500:80"
  #rabbitmq:
  #  ports:
  #    - "5672:5672"
  #redis:
  #  ports:
  #    - "6379:6379"
  #seq:
  #  environment:
  #    - ACCEPT_EULA=Y
  #  ports:
  #    - "5340:80"
  #sqldata:
  #  environment:
  #    - SA_PASSWORD=Pass@word
  #    - ACCEPT_EULA=Y
  #  ports:
  #    - "5433:1433"
  #  volumes:
  #    - eshop-sqldata:/var/opt/mssql
  zipkin:
    ports:
      - "5411:9411"
  dapr-placement:
    command: ["./placement", "-port", "50006", "-log-level", "debug"]

  web.actions.aggregator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:80"
  web.actions.aggregator-dapr:
    command: ["./daprd",
      "-app-id", "aggregate",
      "-app-port", "80",
      "-components-path", "/components"
      ]
    volumes:
      - "./dapr/components/:/components"

  action.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5006:80"
  action.api-dapr:
    command: ["./daprd",
      "-app-id", "action",
      "-app-port", "80",
      "-components-path", "/components"
      ]
    volumes:
      - "./dapr/components/:/components"

  httpclient.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5007:80"
  httpclient.api-dapr:
    command: ["./daprd",
      "-app-id", "httpclient",
      "-app-port", "80",
      "-components-path", "/components"
      ]
    volumes:
      - "./dapr/components/:/components"

  rulecollections.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5003:80"
      #- "51000:51000"
  rulecollections.api-dapr:
    command: ["./daprd",
      "-app-id", "logicapi",
      "-app-port", "80",
      #"-app-port", "51000",
      #"-app-protocol", "grpc",
      "-placement-host-address","placement:50006",
      "-components-path", "/components"
      ]
    volumes:
      - "./dapr/components/:/components"

  managementcollections.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5005:80"
      #- "51000:51000"
  managementcollections.api-dapr:
    command: ["./daprd",
      "-app-id", "managementapi",
      "-app-port", "80",
      #"-app-port", "51000",
      #"-app-protocol", "grpc",
      "-placement-host-address","placement:50006",
      "-components-path", "/components"
      ]
    volumes:
      - "./dapr/components/:/components"

  hr.test:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6001:80"