version: '3.4'

networks:
  efp-dapr:
    driver: bridge

services:
# Deploy other daprized services and components
  #maildev:
  #  image: maildev/maildev
  #rabbitmq:
  #  image: rabbitmq:3-management-alpine
  redis:
    image: redis:latest
    networks:
      - efp-dapr
  #seq:
  #  image: datalust/seq:latest
  #sqldata:
  #  image: mcr.microsoft.com/mssql/server:2017-latest 
  zipkin:
    image: openzipkin/zipkin
  dapr-placement:
    image: "daprio/dapr:1.6.0"
    networks:
      - efp-dapr

  #dynamicwebsite:
  #  image: dynamicwebsite
  #  build:
  #    context: ./webapp
  #    dockerfile: Dockerfile

# Deploy self customized app daprized services

  web.actions.aggregator:
    image: ${DOCKER_REGISTRY-}webactionsaggregator
    build:
      context: .
      dockerfile: src/Web Apps/ApiGateways/Web.Actions.Aggregator/Dockerfile
    networks:
      - efp-dapr
  web.actions.aggregator-dapr:
    image: "daprio/daprd:1.6.0"
    network_mode: "service:web.actions.aggregator"
    depends_on:
      - web.actions.aggregator

  rulecollections.api:
    image: ${DOCKER_REGISTRY-}rulecollectionsapi
    build:
      context: .
      dockerfile: src/Web Apps/Services/CoreProcess/Logic/RuleCollections.API/Dockerfile
    depends_on:
      - redis
    networks:
      - efp-dapr
  rulecollections.api-dapr:
    image: "daprio/daprd:1.6.0"
    network_mode: "service:rulecollections.api"
    depends_on:
      - rulecollections.api

